---
title: "Bacillus selection gradients"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
   - \usepackage{graphics}
output:
  pdf_document:
  fig_caption: true
---

# Initial setup

```{r results='hide', message=FALSE}
rm(list=ls())
# setwd("~/GitHub/coevolution-ts/")
require("dplyr")
require(here)
```

# Load data and standardize trait data (percent sporulation)

```{r}
data <- read.csv(here("data/sporulation-growth.csv"), header = TRUE, sep =",")
# data <- read.csv("./data/sporulation-growth.csv", header = TRUE, sep =",")

#select sporulation data time (24 or 48 hrs)
data <- filter(data, Tsample=="T48H")

perc.spore.std <- (data$perc.spore - mean(data$perc.spore)) / sd(data$perc.spore)
data <- data.frame(data, perc.spore.std)
```

# Calculate relative fitness

```{r}
# average fitness for ancestral strain
anc <- filter(data, host == "WT" & phage == "no_Phage" & line == "ANC") %>%
   dplyr::select(colony, growth.rate) %>%
   group_by(colony) %>%
   summarize(an.growth.rate = mean(growth.rate)) 
anc.gr <- mean(anc$an.growth.rate)
rel.fit <- data$growth.rate / anc.gr
data <- data.frame(data, rel.fit)
```

# Visualize trait variation

```{r}
spore.hist <- hist(data$perc.spore.std, main = NA, 
      xlab = "standardized % sporulation", ylab = "Frequency",
      breaks = 25)
```

# Visualize fitness variation

```{r}
fitness.hist <- hist(data$rel.fit, main = NA, 
      xlab = expression('Relative fitness ('~italic(w)~')'), ylab = "Frequency",
      breaks = 25)
```

# Select strains

```{r}
# Wild type host without seed bank and no phage
wt.np.anc <- filter(data, host == "WT" & phage == "no_Phage" & line == "ANC") %>%
   dplyr::select(colony, line, perc.spore.std, rel.fit) %>%
   group_by(colony) %>%
   summarize(perc.spore.std = mean(perc.spore.std), rel.fit = mean(rel.fit)) 

# Wild type host with short seed bank and no phage
wt.np.short <- filter(data, host == "WT" & phage == "no_Phage" & seed.bank == "short") %>%
   dplyr::select(colony, line, perc.spore.std, rel.fit) %>%
   group_by(colony, line) %>%
   summarize(perc.spore.std = mean(perc.spore.std), rel.fit = mean(rel.fit)) 

# Wild type host with short seed bank and plus phage
wt.pp.short <- filter(data, host == "WT" & phage == "SPO1" & seed.bank == "short") %>%
   dplyr::select(colony, line, perc.spore.std, rel.fit) %>%
   group_by(colony, line) %>%
   summarize(perc.spore.std = mean(perc.spore.std), rel.fit = mean(rel.fit)) 
```

# Plot selection gradient

```{r}
# Wild type ancestor vs. evolved host with a short seed bank

png(filename=here("/plots/selection-gradient/select.grad-1-48h.png"),
    width = 1200, height = 1200, res = 96*2)

plot.new()
par(mar = c(7, 7, 5, 7))

plot(wt.np.anc$perc.spore.std, wt.np.anc$rel.fit, xlim = c(-0.1, 1.1), 
     ylim = c(0.75, 1.4), type = "p", 
     pch = 21, bg = "pink", col = "black", cex = 1.5, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 1, yaxt = "n", xaxt = "n")
box(lwd=2)

# Add ticks and tick labels
axis(side = 2, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
   labels = c("0.75", "1.00", "1.25"), at = c(0.75, 1.0, 1.25))

axis(side = 4, labels = F, lwd.ticks = 2, 
   at = c(0.75, 1.0, 1.25))

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
    labels = c("0.0", "0.25", "0.50", "0.75", "1.0"), at = c(0, 0.25, 0.5, 0.75, 1))

axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
   at = c(0, 0.25, 0.5, 0.75, 1))

mtext('Sporulation (standardized)', side = 1, outer = TRUE, cex = 1.5, 
      line = -4, adj = 0.5)

mtext(expression('Relative fitness ('~italic(w)~')'), side = 2, outer = TRUE, 
      cex = 1.5, line = -3.5, adj = 0.6)

fit1 <- lm(wt.np.anc$rel.fit ~ wt.np.anc$perc.spore.std)
abline(fit1, col = "red", lty = 2, lwd = 2)

points(wt.np.short$perc.spore.std, wt.np.short$rel.fit, type = "p", 
     pch = 21, bg = "lightblue", lwd = 1, col = "black", cex = 1.5)

fit2 <- lm(wt.np.short$rel.fit ~ wt.np.short$perc.spore.std)
abline(fit2, col = "blue", lty = 2, lwd = 2)

dev.off()  
graphics.off() 
```

```{r}
# Short seed bank without phage vs. short seed bank with phage

png(filename=here("/plots/selection-gradient/select.grad-2-48h.png"),
    width = 1200, height = 1200, res = 96*2)

plot.new()
par(mar = c(7, 7, 5, 7))

plot(wt.np.short$perc.spore.std, wt.np.short$rel.fit, xlim = c(-1.5, 1.5), 
     ylim = c(0.65, 1.4), type = "p", 
     pch = 21, bg = "pink", col = "black", cex = 1.5, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 1, yaxt = "n", xaxt = "n")
box(lwd=2)

# Add ticks and tick labels
axis(side = 2, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
   labels = c("0.75", "1.00", "1.25"), at = c(0.75, 1.0, 1.25))

axis(side = 4, labels = F, lwd.ticks = 2, 
   at = c(0.75, 1.0, 1.25))

axis(side = 1, lwd.ticks = 2, cex.axis = 1.2, las = 1,
    labels = c("-1.0", "-0.5", "0.0", "0.5", "1.0"), at = c(-1, -0.5, 0, 0.5, 1))

axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1.2, 
   at = c(-1.0, -0.5, 0, 0.5, 1.0))

mtext('Sporulation (standardized)', side = 1, outer = TRUE, cex = 1.5, 
      line = -4, adj = 0.5)

mtext(expression('Relative fitness ('~italic(w)~')'), side = 2, outer = TRUE, 
      cex = 1.5, line = -3.5, adj = 0.6)

fit1 <- lm(wt.np.short$rel.fit ~ wt.np.short$perc.spore.std)
abline(fit1, col = "red", lty = 2, lwd = 2)

points(wt.pp.short$perc.spore.std, wt.pp.short$rel.fit, type = "p", 
     pch = 21, bg = "lightblue", lwd = 1, col = "black", cex = 1.5)

fit2 <- lm(wt.pp.short$rel.fit ~ wt.pp.short$perc.spore.std)
abline(fit2, col = "blue", lty = 2, lwd = 2)

dev.off()  
graphics.off() 
```

-------------
Compare all treatments

```{r}
library(ggplot2)
library(cowplot)

plot.data <- 
   data%>%
   #add seed.bank ANC to ancestor
   mutate(seed.bank = if_else(line=="ANC","ANC", as.character(seed.bank)))%>%
   #summarize means
   dplyr::select(host, phage, line, seed.bank, colony, perc.spore.std, rel.fit)%>%
   group_by(host, phage, line, colony, seed.bank) %>%
   summarize(n=n(),
             se.spore=sd(perc.spore.std)/sqrt(n),
             se.fit=sd(rel.fit)/sqrt(n),
             perc.spore.std = mean(perc.spore.std),
             rel.fit = mean(rel.fit))
```

Plot all
```{r}

   plot.data %>%
#plot
   ggplot(aes(x=perc.spore.std, y=rel.fit))+
   geom_smooth(method = "lm", linetype=1, se = F, size=1.5, color="black")+
   geom_errorbar(aes(ymin = rel.fit-se.fit, ymax = rel.fit+se.fit,color=seed.bank), width = 0.1,alpha =0.5)+
      geom_errorbarh(aes(xmin = perc.spore.std-se.spore, xmax = perc.spore.std+se.spore,color=seed.bank), height = 0.1, alpha =0.5)+
   geom_point(aes(fill=seed.bank), alpha=0.5,shape=21, size=3)+
   facet_wrap(seed.bank~phage)+
   theme_cowplot()+
   panel_border()+
   xlab('Sporulation (standardized)')+
   ylab(expression('Relative fitness ('~italic(w)~')'))+
   theme(legend.position = "bottom")
   # ggsave(here("plots/selection-gradient/select.grad-phage.png"),
    # width = 10, height = 7)
   
```



Compare across phage treatments
```{r}
#duplicate ancestor data for phage treatment panel
   plot.data %>%
   filter(line == "ANC")%>%
   mutate(phage = "SPO1")%>%
   bind_rows(plot.data, .)%>%
#plot
   ggplot(aes(x=perc.spore.std, y=rel.fit, color=seed.bank))+
   geom_smooth(method = "lm", linetype=1, se = F, size=1.5)+
   geom_point(aes(fill=seed.bank), alpha=0.5,shape=21, size=3)+
   facet_wrap(~phage)+
   theme_cowplot()+
   panel_border()+
   xlab('Sporulation (standardized)')+
   ylab(expression('Relative fitness ('~italic(w)~')'))+
   theme(legend.position = "bottom")+
   ggsave(here("plots/selection-gradient/select.grad-phage.png"),
    width = 10, height = 7)
   
```

Compare across seed bank treatments  
```{r}

plot.data %>%
   filter(line != "ANC")%>%
   ggplot(aes(x=perc.spore.std, y=rel.fit, color=phage))+
   geom_smooth(method = "lm", linetype=1, se = F, size=1.5)+
   geom_point(aes(fill=phage), alpha=0.5,shape=21, size=3)+
   facet_wrap(~seed.bank)+
   theme_cowplot()+
   panel_border()+
   xlab('Sporulation (standardized)')+
   ylab(expression('Relative fitness ('~italic(w)~')'))+
   theme(legend.position = "bottom")+
   ggsave(here("plots/selection-gradient/select.grad-seed.bank.png"),
    width = 10, height = 7)
   
```

