---
title: "Stability analysis for coevolution with a seed bank"
output:
  pdf_document: default
  html_notebook:
    code_folding: hide
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# library(renv)
# #install to project library the required packages
# renv::restore()
# # Initialize lock file when first setting repo
# renv::init()

library(here)
# # set root at project file ("coevolution-ts"). 
# # Done once at initial setup.
# here::set_here()

library(tidyverse)
library(cowplot)
library(car)

# save the state of the project library to the lockfile (called renv.lock),
# renv::snapshot()

```

Load organized data  
```{r, echo=FALSE, message=FALSE}
d <- read_csv(here("data","organized_pop_density.csv"), )

# focus on long vs n seed bank
d <- d %>% 
  filter(seed.bank != "short") %>% 
   mutate(seed.bank = 
            if_else(host=="WT", "+seed bank", "-seed bank"))


```


```{r}
# # Multivariate transformation to normality within levels of 'htype'
# bx.cx <- powerTransform(cell.ml ~ phage*seed.bank*line, d)
# summary(bx.cx)
# 
# 
# d <- d%>%
#   mutate(bxcx.response=bcPower(cell.ml, bx.cx$roundlam))
# 
# # Levene's test with multiple independent variables
# car::leveneTest(bxcx.response ~ phage*seed.bank*line, data = d)
```


```{r, echo=F}
#Calculate stability for each population over time
cell.stab <- 
  d%>%
  #make time by dya
  mutate(Time= Time*2) %>%
  #selecet time period to analyze
  filter(Time>=0)%>%
  # looking only at total cells
  select(Time,flask, host, phage, seed.bank,cell.ml)%>%
  mutate(cell.ml=log10(cell.ml))%>%
  group_by(flask)%>%
  #stability = mean / SD (over time)
  summarise(t.mean=mean(cell.ml), t.sd=sd(cell.ml), stability=t.mean/t.sd)




cell.stab <- 
  cell.stab%>%
    mutate(host=case_when(grepl("W", flask) ~ "WT",
                         grepl("SN", flask) ~ "dSpoIIE",
                         grepl("dS", flask) ~ "dSpoIIE"))%>%
  
    mutate(phage=case_when(grepl("O", flask) ~ "SPO1",
                           grepl("Ct", flask) ~ "no_Phage"))%>%
    
   mutate(seed.bank = 
            if_else(host=="WT", "+seed bank", "-seed bank")) %>%  
    
    mutate(line=str_sub(flask, -2,-1))

#summarise
sum.cell.stab <- 
  cell.stab%>%
    group_by(seed.bank,phage) %>% 
    summarise(
      sd = sd(stability),
      stability = mean(stability))
    
    
  # plot
cell.stab%>%
  ggplot(aes(x=seed.bank, y=stability))+
  geom_crossbar(data=sum.cell.stab,
                  aes(ymin=stability-sd, ymax=stability+sd), width=0.3)+
  geom_dotplot(binaxis='y', stackdir='center', fill="white", alpha=0.5)+
  # geom_jitter(shape=21, fill="grey", size=2, width = 0.05, height = 0)+
  facet_wrap(~phage)+
  theme_cowplot()+
  ggtitle("Observed data on total cell density")
```

Is there statistical support for seed bank stability?

```{r stability stats}
aov_stab <- 
  aov(stability~seed.bank*phage, 
      data = cell.stab)
    # data = filter(cell.stab, phage=="SPO1"))
  
summary(aov_stab)
# plot(aov_stab)
```

Yes, there is! Post-hoc:
```{r}
library(emmeans)

res.emm <- emmeans(aov_stab, c("seed.bank", "phage"))

contrast(res.emm,by="phage", method = "pairwise")

plot(res.emm)+theme_bw()
```

```{r}
library(emmeans)

res.emm <- emmeans(aov_stab, c("seed.bank"))

contrast(res.emm, method = "pairwise")

plot(res.emm)+theme_bw()
```


```{r}
library(emmeans)

res.emm <- emmeans(aov_stab, c("phage"))

contrast(res.emm, method = "pairwise")

plot(res.emm)+theme_bw()
```

```{r}
res.emm <- emmeans(aov_stab, c("seed.bank", "phage"))
contrast(res.emm,by="phage", method = "pairwise")
contrast(res.emm,by="seed.bank", method = "pairwise")
```


# stability over time

```{r}
library(RcppRoll)

win.size <-7

cell.stab.win <- 
  d%>%
  #make time by day
  mutate(Time= Time*2) %>%
  #selecet time period to analyze
  filter(Time>=0)%>%
  # looking only at total cells
  select(Time,flask, host, phage, seed.bank,cell.ml)%>%
  mutate(cell.ml=log10(cell.ml))%>%
  group_by(flask)%>%
  #stability = mean / SD (over time)
  summarise(Time=roll_mean(Time,win.size, align = "center", fill=NA ),
            t.mean=roll_mean(cell.ml,win.size, align = "center", fill=NA ),
            t.sd=roll_sd(cell.ml,win.size, align = "center", fill=NA ),
            stability=t.mean/t.sd)


cell.stab.win <- 
  cell.stab.win%>%
  filter(!is.na(Time))%>%
    mutate(host=case_when(grepl("W", flask) ~ "WT",
                         grepl("SN", flask) ~ "dSpoIIE",
                         grepl("dS", flask) ~ "dSpoIIE"))%>%
  
    mutate(phage=case_when(grepl("O", flask) ~ "SPO1",
                           grepl("Ct", flask) ~ "no_Phage"))%>%
    
   mutate(seed.bank = 
            if_else(host=="WT", "+seed bank", "-seed bank") %>% 
             as_factor() %>% fct_rev()) %>% 
    
    mutate(line=str_sub(flask, -2,-1))

#summarise
sum.cell.stab.win<-
  cell.stab.win%>%
    group_by(Time,seed.bank,phage) %>%
    summarise(
      sd = sd(stability),
      stability = mean(stability),
      n=n())%>%
  mutate(sem=sd/sqrt(n)) %>%
  
  #ajust factor order for seed bank
   # mutate(seed.bank = 
   #          if_else(host=="WT", "+seed bank", "-seed bank") %>% 
   #           as_factor() %>% fct_rev()) %>% 

  mutate (phage = if_else(phage == "no_Phage", "-phage", "+phage")) %>%
    mutate(phage=as.factor(phage))%>%
  mutate(phage = fct_relevel(phage, "+phage","-phage"))

    
    
  # plot
sum.cell.stab.win%>%
ggplot(aes(x=Time, y = stability, color = seed.bank))+
  geom_line()+
  geom_linerange(aes(ymin = stability-sem, ymax = stability+sem),
                 size = 0.5, show.legend = FALSE)+
  geom_point(aes(shape=seed.bank, fill= seed.bank), size = 1.5)+
  facet_wrap( ~ phage)+
      theme_cowplot()+
      panel_border(color = "black", size = 1.5)+
  scale_x_continuous(breaks = c(0,7,14,21,28), limits = c(0,28))+
  scale_shape_manual(values = c(21,22,24))+
  scale_color_viridis_d()+
  scale_fill_viridis_d()+
      theme(legend.position = c(.75, .12),
            legend.title = element_blank(),
            strip.background = element_blank(),
            strip.text = element_text(face = "bold"))+
  ylab("Stability") +
  xlab("Time (days)")-> p
  # xlab("Time (day)")+
  # labs(caption = paste0("stability = mean/SD\nCalculated from log transformed cell abundance data with sliding window of ",win.size, " days" )) 

  # ggsave(here("plots", "stability-window.png"), p,
         # width = 8, height = 5, bg = "white")
  p

```

Is there statistical support for seed bank stability over time?

```{r stabilityXtime stats}
aov_stab_time <- 
  aov(stability~seed.bank*phage*Time, 
      data = cell.stab.win)
    # data = filter(cell.stab, phage=="SPO1"))
  
summary(aov_stab_time)
# plot(aov_stab)
```

Yes, there is! Post-hoc:
```{r}
library(emmeans)

res.emm <- emmeans(aov_stab_time, c("seed.bank", "phage"))
res.emm
plot(res.emm)+theme_bw()
```
```{r}
contrast(res.emm,by="phage", method = "pairwise")
```
```{r}
contrast(res.emm,by="phage", method = "pairwise", at = list(Time = 3:25))
```

```{r}
res.emm <- emmeans(aov_stab_time, c("seed.bank", "phage", "Time"),at = list(Time = 3:25))

p.emm <-  broom::tidy(res.emm) %>% 
   mutate(phage = if_else(phage=="SPO1", "+phage", "-phage")) %>% 
ggplot(aes(x=Time, y = estimate, color = seed.bank))+
  geom_line()+
  geom_linerange(aes(ymin = estimate-std.error, ymax = estimate+std.error),
                 size = 0.5, show.legend = FALSE)+
  geom_point(aes(shape=seed.bank, fill= seed.bank), size = 1.5)+
   ylab("Stability (emmeans)")+
  facet_wrap( ~ phage %>% fct_rev())+
      theme_cowplot()+
      panel_border(color = "black", size = 1.5)+
  scale_x_continuous(breaks = c(0,7,14,21,28), limits = c(0,28))+
  scale_shape_manual(values = c(21,22,24))+
  scale_color_viridis_d()+
  scale_fill_viridis_d()+
      theme(legend.position = c(.75, .12),
            legend.title = element_blank(),
            strip.background = element_blank(),
            strip.text = element_text(face = "bold"))

p.emm
```
<!-- Combine plots -->
```{r}


  # ggsave(here("plots", "stability-window-new.png"), 
  #        plot_grid(p, p.emm, labels = c("(a)", "(b)"), ncol = 1),
  #         width = 6, height = 6, bg = "white")

```


```{r}
coevo.pairs <- contrast(res.emm,by="Time", method = "pairwise")%>%
  broom::tidy()


p.pval <- coevo.pairs %>% 
  filter(contrast %in% c("(-seed bank no_Phage) - (+seed bank no_Phage)",
                         "(-seed bank SPO1) - (+seed bank SPO1)")) %>% 
  mutate(phage = if_else(str_detect(contrast, "SPO1"), "+phage", "-phage") %>% fct_rev()) %>% 
  mutate(seed.bank = "-seed bank VS +seed bank") %>% 
  # mutate(contrast = str_replace_all(contrast, "SPO1", "+phage")) %>% 
  # mutate(contrast = str_replace_all(contrast, "no_Phage", "-phage")) %>% 
  #  mutate(contrast = str_replace(contrast, "\\) - \\(", "\nVS\n")) %>% 
  # mutate(contrast = str_remove_all(contrast, "\\(")) %>% 
  #   mutate(contrast = str_remove_all(contrast, "\\)")) %>% 
  ggplot(aes(Time, -log10(adj.p.value)))+
  geom_hline(yintercept = -log10(0.05), color = "red")+
  geom_line()+ 
  geom_point(shape = 21, size=2, fill = "white")+
  geom_text(x = 0, y = -.8,label = expression("adj. "*italic(P)*" = 0.05"),color = "red", hjust =0)+
  facet_wrap(phage~seed.bank )+
  scale_y_reverse()+
  scale_x_continuous(breaks = c(0,7,14,21,28), limits = c(0,28))+
  theme_cowplot()+
  panel_border(color = "black", size = 1.5)+
  panel_border(color = "black")+
  ylab(expression("-log"[10]*" adjusted "*italic(P)*" value"))+
  xlab("Time (days)")+
        theme(legend.title = element_blank(),
            strip.background = element_blank(),
            strip.text = element_text(face = "bold"))
  
p.pval
```

Combine plots
```{r}


  ggsave(here("plots", "stability-window-new.png"),
         plot_grid(p, p.pval, labels = c("(a)", "(b)"), ncol = 1),
          width = 6, height = 6, bg = "white")

```

